export const SEGMENTS = [
  {
    id: "padaria",
    icon: "🍞",
    label: "Padaria",
    accent:    "#F26522",
    accentDim: "rgba(242,101,34,.18)",
    accentGlow:"rgba(242,101,34,.08)",
    headline:  ["Pare de pagar taxa", "pra quem não", "assa nada."],
    accentWord: 1,
    sub: "Site com sua marca, encomendas pagas online, Agente IA no WhatsApp e clube de fidelidade. Seus clientes ficam com você — não com o marketplace.",
    cta:       "Quero meu sistema",
    ctaDemo:   "Ver demonstração",
    channels:  ["iFood", "WhatsApp", "PIX", "Encomendas", "Site"],
    stat:      { val: "+38%", label: "em vendas diretas", desc: "nos primeiros 60 dias" },
    pains: [
      {
        num: "01",
        title: "iFood leva até 30% do que você assa.",
        body: "Comissão, taxa de entrega subsidiada, desconto obrigatório. Cada pedido pelo marketplace custa quase um terço da sua margem. Em vendas diretas, esse dinheiro é todo seu.",
      },
      {
        num: "02",
        title: "Encomenda no papel é encomenda perdida.",
        body: "Anotação no balcão, mensagem no WhatsApp pessoal, promessa verbal. Na sexta-feira o bolo não está feito e o cliente não volta. Uma plataforma organiza tudo com pagamento antecipado.",
      },
      {
        num: "03",
        title: "Seu cliente mais fiel não tem benefício nenhum.",
        body: "Ele compra toda manhã há dois anos, mas não acumula pontos, não recebe oferta exclusiva e não tem motivo para não experimentar o concorrente que abriu semana passada.",
      },
    ],
    testimonial: {
      text: "Em dois meses com a plataforma, as vendas diretas subiram 38%. Paramos de pagar comissão no que era pedido via WhatsApp. O dinheiro que ficava no iFood agora fica com a gente.",
      name: "Carlos Menezes",
      role: "Padaria Dom Trigo · Florianópolis, SC",
      init: "C",
    },
  },

  {
    id: "cafe",
    icon: "☕",
    label: "Café",
    accent:    "#7C4220",
    accentDim: "rgba(124,66,32,.22)",
    accentGlow:"rgba(124,66,32,.09)",
    headline:  ["Seu café tem alma.", "Seu sistema de vendas", "deveria ter também."],
    accentWord: 0,
    sub: "QR code na mesa, assinatura de café, pedidos pelo WhatsApp com Agente IA e painel de produção na tela — sem comissão de ninguém.",
    cta:       "Digitalizar meu café",
    ctaDemo:   "Ver demonstração",
    channels:  ["QR Code", "WhatsApp", "Assinatura", "PIX", "Site"],
    stat:      { val: "+22%", label: "no ticket médio", desc: "com pedido pelo QR code" },
    pains: [
      {
        num: "01",
        title: "Fila no balcão às 8h é cliente perdido.",
        body: "No pico da manhã, quem não quer esperar vai embora. Com pedido pelo WhatsApp ou QR code na mesa, o cliente pede antes de sentar — você produz, ele chega, retira.",
      },
      {
        num: "02",
        title: "O iFood sabe quem é seu cliente. Você, não.",
        body: "E-mail, histórico de consumo, frequência de visita — tudo fica no banco de dados da plataforma. Você nunca tem esses dados para fazer campanhas de reativação ou clube de fidelidade.",
      },
      {
        num: "03",
        title: "Fidelidade é cafezinho bom e nada mais.",
        body: "Sem clube de pontos, sem notificação automática, sem campanha de aniversário, qualquer concorrente que abrir com um cupom de desconto vai roubar metade da sua manhã.",
      },
    ],
    testimonial: {
      text: "O QR code na mesa aumentou nosso ticket médio em 22%. O cliente pede sem precisar chamar, acumula pontos e a fila no balcão caiu pela metade. É outra operação.",
      name: "Priya Mendonça",
      role: "Café Grão Nobre · Belo Horizonte, MG",
      init: "P",
    },
  },

  {
    id: "restaurante",
    icon: "🍽️",
    label: "Restaurante",
    accent:    "#1B7A3E",
    accentDim: "rgba(27,122,62,.20)",
    accentGlow:"rgba(27,122,62,.08)",
    headline:  ["Menos 27% de taxa.", "Mais margem para", "quem cozinha de verdade."],
    accentWord: 0,
    sub: "Site de delivery com sua marca, reservas pelo WhatsApp, cardápio digital e programa de fidelidade — sem intermediário entre você e seu cliente.",
    cta:       "Quero delivery próprio",
    ctaDemo:   "Ver demonstração",
    channels:  ["iFood", "Reservas", "WhatsApp", "PIX", "Site"],
    stat:      { val: "−27%", label: "em comissão paga", desc: "migrando para canal direto" },
    pains: [
      {
        num: "01",
        title: "iFood e Rappi levam até 30% do prato.",
        body: "Comissão, frete subsidiado, listing pago, desconto obrigatório em campanhas. Depois de tudo isso, o restaurante que aparece primeiro na busca às vezes opera no prejuízo sem saber.",
      },
      {
        num: "02",
        title: "Reserva por ligação, no-show sem aviso.",
        body: "Sem sistema de reservas, você não manda lembrete, não cobra antecipado, não tem histórico. Mesa reservada às 20h que não aparece é prejuízo direto sem nenhum dado para evitar da próxima vez.",
      },
      {
        num: "03",
        title: "O cliente é do marketplace. Você é o fornecedor.",
        body: "Quando ele pede pelo iFood, o CPF e o e-mail vão para o iFood. Você faz o prato, eles ficam com o relacionamento. Sem os dados do cliente, você não existe fora da plataforma.",
      },
    ],
    testimonial: {
      text: "Em seis meses, saímos de 80% dos pedidos pelo iFood para 45%. O ticket da plataforma própria é 18% maior e a margem no delivery direto dobrou. Foi a melhor decisão do ano.",
      name: "Roberto Takahashi",
      role: "Restaurante Prato Cheio · São Paulo, SP",
      init: "R",
    },
  },

  {
    id: "adega",
    icon: "🍷",
    label: "Adega",
    accent:    "#821845",
    accentDim: "rgba(130,24,69,.20)",
    accentGlow:"rgba(130,24,69,.08)",
    headline:  ["Sua adega é destino.", "Trate seus clientes", "como membros."],
    accentWord: 0,
    sub: "Clube de assinantes com curadoria mensal, loja online, pedidos especiais pelo WhatsApp com Agente IA e gestão de eventos — tudo com a identidade da sua adega.",
    cta:       "Montar minha adega digital",
    ctaDemo:   "Ver demonstração",
    channels:  ["Clube", "Loja Online", "WhatsApp", "Eventos", "PIX"],
    stat:      { val: "140", label: "assinantes em 4 meses", desc: "com clube estruturado" },
    pains: [
      {
        num: "01",
        title: "Marketplace de vinho destrói preço e marca.",
        body: "Aparecer na mesma prateleira digital de importadora de baixo custo força desconto de sobrevivência. Cliente que compra experiência não está no lugar onde tudo compete por preço.",
      },
      {
        num: "02",
        title: "Clube em planilha é pesadelo todo mês.",
        body: "Sem plataforma, curadoria, cobrança recorrente e logística de cada assinante viram horas de trabalho manual. Você perde mais tempo administrando do que escolhendo os vinhos.",
      },
      {
        num: "03",
        title: "Evento lotado, nenhum dado capturado.",
        body: "Degustação, jantar harmonizado, noite de espumantes — casa cheia. Mas sem check-in digital, amanhã você não sabe quem foi, não tem o e-mail de ninguém e não pode convidar de volta.",
      },
    ],
    testimonial: {
      text: "O clube saiu do zero para 140 assinantes em quatro meses. Receita recorrente, sem marketplace, sem comissão. Agora sei o nome, o gosto e o histórico de cada cliente.",
      name: "Ana Luísa Ferreira",
      role: "Adega Terroir · Curitiba, PR",
      init: "A",
    },
  },
];
