export const SEGMENTS = [
  {
    id: "padaria",
    icon: "🍞",
    label: "Padaria",
    accent: "#B8421A",
    glow: "rgba(184,66,26,.28)",
    glowAlt: "rgba(184,66,26,.10)",
    headline: ["Sua padaria no digital,", "sem abrir mão", "do que é seu."],
    sub: "Site e app próprios, robô no WhatsApp, gestão de encomendas e clube de fidelidade — tudo integrado, tudo com a sua marca.",
    cta: "Quero meu sistema →",
    ctaSecondary: "Ver demonstração",
    channels: ["iFood", "WhatsApp", "App Próprio", "PIX", "PDV"],
    pains: [
      {
        icon: "💸",
        title: "30% de taxa no iFood todo mês",
        desc: "Você trabalha, eles lucram. Cada pedido pelo marketplace custa quase um terço da sua margem. Quem paga essa conta é você.",
      },
      {
        icon: "📋",
        title: "Encomendas perdidas e sem controle",
        desc: "Anotação no papel, mensagem no WhatsApp pessoal, promessa verbal — e na sexta-feira a bolo não está feito. Erros custam clientes.",
      },
      {
        icon: "😶",
        title: "Cliente fiel sem nenhuma fidelização",
        desc: "Aquela cliente que compra toda manhã não tem pontos, não recebe oferta, e amanhã pode virar cliente do concorrente sem que você saiba.",
      },
    ],
    testimonial: {
      name: "Carlos Menezes",
      role: "Padaria Dom Trigo · Florianópolis, SC",
      text: "Em 2 meses do app, as vendas diretas subiram 38%. Paramos de pagar taxa pro iFood no que era pedido via WhatsApp.",
      initial: "C",
    },
  },
  {
    id: "cafe",
    icon: "☕",
    label: "Café",
    accent: "#7C4A1E",
    glow: "rgba(124,74,30,.30)",
    glowAlt: "rgba(124,74,30,.10)",
    headline: ["Do balcão ao delivery,", "sem perder", "a alma do seu café."],
    sub: "Cardápio digital com QR code, assinatura de café, pedidos via WhatsApp e painel de produção na tela — sem tablet de terceiro, sem taxa.",
    cta: "Digitalizar meu café →",
    ctaSecondary: "Ver demonstração",
    channels: ["WhatsApp", "QR Code", "App Próprio", "PIX", "Assinatura"],
    pains: [
      {
        icon: "⌚",
        title: "Fila no balcão e cliente perdido",
        desc: "Nos horários de pico, o cliente vai embora antes de pedir. Sem pedido antecipado pelo app ou WhatsApp, você perde venda toda manhã.",
      },
      {
        icon: "🔗",
        title: "Depende do app de terceiro para tudo",
        desc: "iFood, Rappi, Méliuz — cada um cobra sua fatia e nenhum te dá os dados do cliente. Você nunca sabe quem compra, quanto gasta e quando volta.",
      },
      {
        icon: "🎯",
        title: "Fidelidade é boca a boca e nada mais",
        desc: "Você confia no cafezinho gostoso. Mas sem clube de pontos, sem push notification e sem campanha automática, o concorrente vai roubar seu cliente com um cupom.",
      },
    ],
    testimonial: {
      name: "Priya Mendonça",
      role: "Café Grão Nobre · Belo Horizonte, MG",
      text: "O QR Code na mesa aumentou o ticket médio em 22%. O cliente pede sem chamar garçom e ainda acumula pontos. A fila do balcão caiu pela metade.",
      initial: "P",
    },
  },
  {
    id: "restaurante",
    icon: "🍽️",
    label: "Restaurante",
    accent: "#1A5C3A",
    glow: "rgba(26,92,58,.28)",
    glowAlt: "rgba(26,92,58,.10)",
    headline: ["Delivery próprio, casa cheia,", "menos taxa", "e mais lucro."],
    sub: "App de delivery com sua marca, reservas pelo WhatsApp, cardápio de encomendas e programa de fidelidade — tudo no seu controle, sem intermediário.",
    cta: "Quero delivery próprio →",
    ctaSecondary: "Ver demonstração",
    channels: ["iFood", "App Próprio", "WhatsApp", "PIX", "Reservas"],
    pains: [
      {
        icon: "📉",
        title: "iFood e Rappi comem sua margem",
        desc: "Entre comissão, taxa de entregador e promoção obrigatória, sobra menos de 60% do preço do prato. No seu próprio app, você fica com quase tudo.",
      },
      {
        icon: "📵",
        title: "Reservas por ligação e WhatsApp pessoal",
        desc: "Mesa pedida pelo WhatsApp da garçonete, confirmação verbal, sem histórico. No fim do mês você não sabe quantas mesas reservaram nem quais cancelaram.",
      },
      {
        icon: "📦",
        title: "Zero dados sobre quem é seu cliente",
        desc: "O iFood sabe quem compra no seu restaurante. Você, não. Sem e-mail, sem CPF, sem histórico de pedido — impossível fazer campanha de reativação ou programa de fidelidade.",
      },
    ],
    testimonial: {
      name: "Roberto Takahashi",
      role: "Restaurante Prato Cheio · São Paulo, SP",
      text: "Saímos de 80% dos pedidos pelo iFood para 45% em seis meses. O ticket do app próprio é 18% maior e a margem dobrou no delivery direto.",
      initial: "R",
    },
  },
  {
    id: "adega",
    icon: "🍷",
    label: "Adega",
    accent: "#6B1A4A",
    glow: "rgba(107,26,74,.30)",
    glowAlt: "rgba(107,26,74,.10)",
    headline: ["Sua adega, seu clube,", "sua margem —", "nada de marketplace."],
    sub: "Clube de assinantes, loja online de vinhos e destilados, WhatsApp para pedidos e eventos especiais — com a identidade da sua adega, sem comissão de terceiro.",
    cta: "Montar minha adega digital →",
    ctaSecondary: "Ver demonstração",
    channels: ["Loja Online", "WhatsApp", "Clube", "PIX", "Eventos"],
    pains: [
      {
        icon: "🏷️",
        title: "Marketplace destrói seu preço e marca",
        desc: "Aparecer no mesmo lugar que concorrente de baixo custo força desconto. Quem compra vinho num app de supermercado não é o seu cliente — você está no lugar errado.",
      },
      {
        icon: "📭",
        title: "Sem clube de assinantes estruturado",
        desc: "Muita adega tenta clube por planilha e WhatsApp manual. Sem plataforma própria, as curadoria, cobranças recorrentes e logística viram um pesadelo todo mês.",
      },
      {
        icon: "🎪",
        title: "Evento cheio, mas nenhum dado capturado",
        desc: "Você faz degustação, jazz e jantar harmonizado — a casa lota. Mas sem cadastro, sem check-in digital, você não sabe quem foi e não pode convidar de novo.",
      },
    ],
    testimonial: {
      name: "Ana Luísa Ferreira",
      role: "Adega Terroir · Curitiba, PR",
      text: "O clube de assinantes saiu do zero para 140 clientes em 4 meses com a plataforma. Receita recorrente, sem marketplace, sem comissão. É outra vida.",
      initial: "A",
    },
  },
];
